### ISSUE TITLE
Copy Mallet Folder into '/content'

### ISSUE THREAD

**Issue by mahakud1** [polsci/colab-gensim-mallet#1]
Hi, Could you please help in terms of how can I copy the mallet folder to '/content/' folder under google drive. As I can only see till 'My Drive'

**Comment by polsci** [comment]
Sorry, I'm looking at this after a while and pleasantly surprised people have used this. I'm unsure what you are asking here. I'm sure you've worked it out, but if anyone sees this a good place to start is the Colab documentation.
